// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/pusrenk/auth-service/internal/user/entities"
	mock "github.com/stretchr/testify/mock"
)

// UserServiceMock is an autogenerated mock type for the UserService type
type UserServiceMock struct {
	mock.Mock
}

type UserServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserServiceMock) EXPECT() *UserServiceMock_Expecter {
	return &UserServiceMock_Expecter{mock: &_m.Mock}
}

// GetUserBySessionID provides a mock function with given fields: ctx, sessionID
func (_m *UserServiceMock) GetUserBySessionID(ctx context.Context, sessionID string) (*entities.User, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBySessionID")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserServiceMock_GetUserBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBySessionID'
type UserServiceMock_GetUserBySessionID_Call struct {
	*mock.Call
}

// GetUserBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *UserServiceMock_Expecter) GetUserBySessionID(ctx interface{}, sessionID interface{}) *UserServiceMock_GetUserBySessionID_Call {
	return &UserServiceMock_GetUserBySessionID_Call{Call: _e.mock.On("GetUserBySessionID", ctx, sessionID)}
}

func (_c *UserServiceMock_GetUserBySessionID_Call) Run(run func(ctx context.Context, sessionID string)) *UserServiceMock_GetUserBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserServiceMock_GetUserBySessionID_Call) Return(_a0 *entities.User, _a1 error) *UserServiceMock_GetUserBySessionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserServiceMock_GetUserBySessionID_Call) RunAndReturn(run func(context.Context, string) (*entities.User, error)) *UserServiceMock_GetUserBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// StoreUserSession provides a mock function with given fields: ctx, user
func (_m *UserServiceMock) StoreUserSession(ctx context.Context, user *entities.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for StoreUserSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserServiceMock_StoreUserSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreUserSession'
type UserServiceMock_StoreUserSession_Call struct {
	*mock.Call
}

// StoreUserSession is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entities.User
func (_e *UserServiceMock_Expecter) StoreUserSession(ctx interface{}, user interface{}) *UserServiceMock_StoreUserSession_Call {
	return &UserServiceMock_StoreUserSession_Call{Call: _e.mock.On("StoreUserSession", ctx, user)}
}

func (_c *UserServiceMock_StoreUserSession_Call) Run(run func(ctx context.Context, user *entities.User)) *UserServiceMock_StoreUserSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.User))
	})
	return _c
}

func (_c *UserServiceMock_StoreUserSession_Call) Return(_a0 error) *UserServiceMock_StoreUserSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserServiceMock_StoreUserSession_Call) RunAndReturn(run func(context.Context, *entities.User) error) *UserServiceMock_StoreUserSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserServiceMock creates a new instance of UserServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceMock {
	mock := &UserServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
